/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyChildComponent {}
  interface MyParentComponent {}
}

declare global {


  interface HTMLMyChildComponentElement extends Components.MyChildComponent, HTMLStencilElement {}
  var HTMLMyChildComponentElement: {
    prototype: HTMLMyChildComponentElement;
    new (): HTMLMyChildComponentElement;
  };

  interface HTMLMyParentComponentElement extends Components.MyParentComponent, HTMLStencilElement {}
  var HTMLMyParentComponentElement: {
    prototype: HTMLMyParentComponentElement;
    new (): HTMLMyParentComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-child-component': HTMLMyChildComponentElement;
    'my-parent-component': HTMLMyParentComponentElement;
  }
}

declare namespace LocalJSX {
  interface MyChildComponent {}
  interface MyParentComponent {}

  interface IntrinsicElements {
    'my-child-component': MyChildComponent;
    'my-parent-component': MyParentComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-child-component': LocalJSX.MyChildComponent & JSXBase.HTMLAttributes<HTMLMyChildComponentElement>;
      'my-parent-component': LocalJSX.MyParentComponent & JSXBase.HTMLAttributes<HTMLMyParentComponentElement>;
    }
  }
}


